### ISSUE TITLE
[KiPart BUG] Wrong unit sorting order (A, AA, AB, AC, B, ...)

### ISSUE THREAD

**Issue by dsa-t** [devbisme/KiPart#66]
**Describe the bug**
I have a pin table with units specified.

The problem is that units doesn't match KiCad names:

| KiCad unit name | CSV unit name | 
| - | - |
A | A
B | AA
C | AB
D | AC
E | B
... | ...

**Expected behavior**
I expect the KiCad unit names to match the unit names provided in the CSV table:

| KiCad unit name | CSV unit name | 
| - | - |
A | A
B | B
... | ...
AA | AA
AB | AB
AC | AC
... | ...

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.9.12
 - KiPart version: 1.0.0

**Comment by dnschneid** [comment]
The unit name in the CSV isn't passed along to KiCad.  It uniquely defines the unit that the pin should be put into, and the units are output to KiCad in the order the first pin in the unit appears in the CSV.

So your unit name can be anything, and the first unit in the csv will end up as unit A, the second unique unit found in the csv will be B, etc.

**Comment by dsa-t** [comment]
Ok, I can make it work as intended if I rename double-digit units to ZA, ZB, ZC. And the unit sorting still works.

Now this issue can be turned into a feature-request to add an option to control the unit sorting 🙂.

**Comment by dnschneid** [comment]
Oops, I remembered wrong.  The units are tracked in a python dictionary, which is unordered.  The units are then written out in lexicographical order.

Having the option to maintain the order that they appear in the CSV would be nice, I guess.

**Comment by dsa-t** [comment]
Probably there should be like three options: "Do not sort", "Sort like KiCad", "Sort lexicographically"
