### ISSUE TITLE
Add Zynq-7000 Series Package Devices Pinoput Files from Xilinx

### ISSUE THREAD

**Issue by Knochi** [devbisme/KiPart#72]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would like to see -r option for [Xilinx Zynq-7000 SoC](https://www.xilinx.com/support/package-pinout-files/zynq7000-pkgs.html) Package Files 

**Describe alternatives you've considered**
manually edited the csv file to be imported generic

**Additional context**
nothing to add

**Comment by devbisme** [comment]
Have you looked in the Xilinx libraries [here](https://github.com/devbisme/KiCad-Schematic-Symbol-Libraries/tree/master/xilinx)? Maybe the part you need is already available.

**Comment by Knochi** [comment]
Hi @devbisme 
thanks for the tip.

the fact that i found the symbol in the lib you linked made me try again with kipart.

So when i extract only the chip I need from zip i downloaded at xilinx this gives me an empty library.
```
kipart -r xilinx7 xc7z020clg484pkg.txt
Writing xc7z020clg484pkg.lib 0
```
But when i insert the whole zip, I get all of them
```
kipart -r xilinx7 z7all.zip
Writing z7all.lib 22
``` 

So the xilinx7 option kinda works for z7 chips as well.
